// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCharacterAPI.Models;

namespace MovieCharacterAPI.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.Property<int>("CharactersCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("CharactersCharacterId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("CharacterMovie");

                    b.HasData(
                        new
                        {
                            CharactersCharacterId = 1,
                            MoviesMovieId = 1
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            MoviesMovieId = 2
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            MoviesMovieId = 3
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            MoviesMovieId = 3
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            MoviesMovieId = 3
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            MoviesMovieId = 4
                        },
                        new
                        {
                            CharactersCharacterId = 4,
                            MoviesMovieId = 4
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            MoviesMovieId = 5
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            MoviesMovieId = 5
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            MoviesMovieId = 5
                        },
                        new
                        {
                            CharactersCharacterId = 4,
                            MoviesMovieId = 5
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CharacterId");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Alias = "Iron Man",
                            FullName = "Robert Downey Jr.",
                            Gender = "Male"
                        },
                        new
                        {
                            CharacterId = 2,
                            Alias = "Thor",
                            FullName = "Chris Hemsworth",
                            Gender = "Male"
                        },
                        new
                        {
                            CharacterId = 3,
                            Alias = "Captain America",
                            FullName = "Chris Evans",
                            Gender = "Male"
                        },
                        new
                        {
                            CharacterId = 4,
                            Alias = "Spider Man",
                            FullName = "Tom Holland",
                            Gender = "Male"
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchise");

                    b.HasData(
                        new
                        {
                            FranchiseId = 1,
                            Name = "Iron Man Series"
                        },
                        new
                        {
                            FranchiseId = 2,
                            Name = "Spider Man Series"
                        },
                        new
                        {
                            FranchiseId = 3,
                            Name = "Thor Series"
                        },
                        new
                        {
                            FranchiseId = 4,
                            Name = "Captain America Series"
                        },
                        new
                        {
                            FranchiseId = 5,
                            Name = "Marvel Universe"
                        });
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrailerURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Jon Favreau",
                            FranchiseId = 1,
                            Genre = "Comic Book,Superhero",
                            ReleaseYear = 2008,
                            Title = "Iron Man"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Kenneth Branagh",
                            FranchiseId = 3,
                            Genre = "Comic Book,Superhero",
                            ReleaseYear = 2011,
                            Title = "Thor"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Joss Whedon",
                            FranchiseId = 5,
                            Genre = "Comic Book, Superhero",
                            ReleaseYear = 2012,
                            Title = "The Avengers"
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "Jon Watts",
                            FranchiseId = 2,
                            Genre = "Comic Book, Superhero",
                            ReleaseYear = 2017,
                            Title = "SpiderMan Homecoming"
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "Anthony and Joe Russo",
                            FranchiseId = 5,
                            Genre = "Comic Book, Superhero",
                            ReleaseYear = 2018,
                            Title = "Avengers: Infinity War"
                        });
                });

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.HasOne("MovieCharacterAPI.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCharacterAPI.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Movie", b =>
                {
                    b.HasOne("MovieCharacterAPI.Models.Franchise", "Franchise")
                        .WithMany("Movie")
                        .HasForeignKey("FranchiseId");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("MovieCharacterAPI.Models.Franchise", b =>
                {
                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
